# Development stage
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Install development dependencies
COPY package*.json ./
RUN npm install

# Set environment variables
ENV NODE_ENV=development
ENV PORT=3000
ENV HOST=0.0.0.0

# Expose port
EXPOSE 3000


# Start development server
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"] 