services:
  # Test database
  postgres:
    image: postgres:16-alpine
    container_name: postgres-db-test
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./backend/src/config/db/init:/docker-entrypoint-initdb.d
    networks:
      - test-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend development server for e2e tests
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    container_name: backend-test
    environment:
      NODE_ENV: development
      PORT: 5000
      HOST: 0.0.0.0
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      FIREBASE_SERVICE_ACCOUNT: ${FIREBASE_SERVICE_ACCOUNT}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    expose:
      - "5000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - test-network
    command: npm run dev
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  # Frontend development server for e2e tests
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: frontend-test
    environment:
      NODE_ENV: development
      PUBLIC_BACKEND_API_URL: http://backend:5000/api
      PUBLIC_FIREBASE_API_KEY: ${PUBLIC_FIREBASE_API_KEY}
      PUBLIC_FIREBASE_AUTH_DOMAIN: ${PUBLIC_FIREBASE_AUTH_DOMAIN}
      PUBLIC_FIREBASE_PROJECT_ID: ${PUBLIC_FIREBASE_PROJECT_ID}
      PUBLIC_FIREBASE_STORAGE_BUCKET: ${PUBLIC_FIREBASE_STORAGE_BUCKET}
      PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
      PUBLIC_FIREBASE_APP_ID: ${PUBLIC_FIREBASE_APP_ID}
    expose:
      - "3000"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - test-network
    command: npm run dev -- --host 0.0.0.0
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  # E2E tests
  e2e-test:
    build:
      context: ./e2e
      dockerfile: Dockerfile
    environment:
      NODE_ENV: test
      BACKEND_URL: http://backend:5000
      FRONTEND_URL: http://frontend:3000
      PUBLIC_FIREBASE_API_KEY: ${PUBLIC_FIREBASE_API_KEY}
      PUBLIC_FIREBASE_AUTH_DOMAIN: ${PUBLIC_FIREBASE_AUTH_DOMAIN}
      PUBLIC_FIREBASE_PROJECT_ID: ${PUBLIC_FIREBASE_PROJECT_ID}
      PUBLIC_FIREBASE_STORAGE_BUCKET: ${PUBLIC_FIREBASE_STORAGE_BUCKET}
      PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
      PUBLIC_FIREBASE_APP_ID: ${PUBLIC_FIREBASE_APP_ID}
    volumes:
      - ./e2e:/app
      - /app/node_modules
    networks:
      - test-network
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    profiles:
      - e2e
    command: npm test

volumes:
  postgres_test_data:

networks:
  test-network:
    driver: bridge
