version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: budgetwise_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/config/db/init:/docker-entrypoint-initdb.d
    networks:
      - budgetwise_network
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: ${DOCKER_REGISTRY:-ghcr.io}/${GITHUB_REPOSITORY:-your-username/budgetwise}/backend:${GITHUB_SHA:-latest}
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: budgetwise_backend
    environment:
      NODE_ENV: production
      POSTGRES_HOST: postgres
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - budgetwise_network
    restart: always

  frontend:
    image: ${DOCKER_REGISTRY:-ghcr.io}/${GITHUB_REPOSITORY:-your-username/budgetwise}/frontend:${GITHUB_SHA:-latest}
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: budgetwise_frontend
    ports:
      - "80:80" # Changed to port 80 for production
    networks:
      - budgetwise_network
    restart: always

volumes:
  postgres_data:


networks:
  budgetwise_network:
    driver: bridge
