version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: budgetwise_db_dev
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-budgetwise}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/config/db/init:/docker-entrypoint-initdb.d
    networks:
      - budgetwise_network_dev
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: budgetwise_backend_dev
    environment:
      NODE_ENV: development
      POSTGRES_HOST: postgres
      POSTGRES_DB: ${POSTGRES_DB:-budgetwise}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      JWT_SECRET: ${JWT_SECRET:-your-secret-key}
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - budgetwise_network_dev
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: budgetwise_frontend_dev
    environment:
      - VITE_API_URL=http://localhost:5000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - budgetwise_network_dev
    command: npm run dev -- --port 3000

volumes:
  postgres_data:


networks:
  budgetwise_network_dev:
    driver: bridge
