# Development stage
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Install development dependencies
COPY package*.json ./
COPY .env .env
RUN npm install

# Set environment variables
ENV NODE_ENV=development
ENV PORT=5000
ENV HOST=0.0.0.0

# Expose port
EXPOSE 5000



# Start development server with hot reload
CMD ["npm", "run", "dev"] 