name: CI Pipeline

on:
  push:
    branches: [main, develop, new-frontend-test]
  pull_request:
    branches: [main, develop]

jobs:
  test-backend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

      - name: Install backend dependencies
        run: |
          cd backend
          npm ci

      - name: Run backend tests
        run: |
          cd backend
          npm test

      - name: Run backend tests with coverage
        run: |
          cd backend
          npm run test:coverage

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          directory: backend/coverage
          flags: backend

  test-frontend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      - name: Build frontend
        run: |
          cd frontend
          npm run build

  # integration-test:
  #   runs-on: ubuntu-latest
  #   needs: [test-backend, test-frontend]
  #   # TODO: Implement integration tests when ready
  #   # Currently disabled as E2E tests are not implemented yet

  docker-build:
    runs-on: ubuntu-latest
    needs: [test-backend, test-frontend]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend Docker image
        run: |
          docker build -t budgetwise-backend ./backend

      - name: Build frontend Docker image
        run: |
          docker build -t budgetwise-frontend ./frontend

      - name: Test Docker containers
        run: |
          # Test that containers can be built and run
          docker run --rm -d --name test-backend budgetwise-backend
          docker run --rm -d --name test-frontend budgetwise-frontend
          sleep 5
          docker stop test-backend test-frontend

  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run security audit on backend
        run: |
          cd backend
          npm audit --audit-level moderate

      - name: Run security audit on frontend
        run: |
          cd frontend
          npm audit --audit-level moderate
