name: Test Suite

on:
  push:
    branches: [main, develop, front-back-testing, deploy-test]
  pull_request:
    branches: [main, develop]

env:
  # Database configuration
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

  # Backend configuration
  FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
  ADMIN_EMAIL: admin@budgetwise.test
  GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

  # Frontend configuration
  PUBLIC_BACKEND_API_URL: ${{ secrets.PUBLIC_BACKEND_API_URL }}
  PUBLIC_FIREBASE_API_KEY: ${{ secrets.PUBLIC_FIREBASE_API_KEY }}
  PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.PUBLIC_FIREBASE_AUTH_DOMAIN }}
  PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.PUBLIC_FIREBASE_PROJECT_ID }}
  PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.PUBLIC_FIREBASE_STORAGE_BUCKET }}
  PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
  PUBLIC_FIREBASE_APP_ID: ${{ secrets.PUBLIC_FIREBASE_APP_ID }}

jobs:
  # Backend Unit Tests
  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci

      - name: Run backend tests
        working-directory: ./backend
        env:
          NODE_ENV: test
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          FIREBASE_SERVICE_ACCOUNT: ${{ env.FIREBASE_SERVICE_ACCOUNT }}
          ADMIN_EMAIL: ${{ env.ADMIN_EMAIL }}
          GEMINI_API_KEY: ${{ env.GEMINI_API_KEY }}
        run: npm test

  # Frontend Unit Tests
  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run frontend tests
        working-directory: ./frontend
        env:
          NODE_ENV: test
        run: npm run test:run

  # E2E Tests (Production Mode)

  docker-build:
    runs-on: ubuntu-latest
    needs: [backend-tests, frontend-tests]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend Docker image
        run: |
          docker build -t budgetwise-backend ./backend

      - name: Build frontend Docker image
        run: |
          docker build -t budgetwise-frontend ./frontend

      - name: Test Docker containers
        env:
          # Backend environment variables
          PORT: "5000"
          POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          POSTGRES_HOST: "localhost"
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          # Frontend environment variables
          PUBLIC_BACKEND_API_URL: ${{ secrets.PUBLIC_BACKEND_API_URL }}
          PUBLIC_FIREBASE_API_KEY: ${{ secrets.PUBLIC_FIREBASE_API_KEY }}
          PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.PUBLIC_FIREBASE_AUTH_DOMAIN }}
          PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.PUBLIC_FIREBASE_PROJECT_ID }}
          PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.PUBLIC_FIREBASE_STORAGE_BUCKET }}
          PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
          PUBLIC_FIREBASE_APP_ID: ${{ secrets.PUBLIC_FIREBASE_APP_ID }}
        run: |
          # Test that containers can be built and run
          echo "Starting backend container..."
          BACKEND_ID=$(docker run --rm -d --name test-backend \
            -e PORT="$PORT" \
            -e POSTGRES_DB="$POSTGRES_DB" \
            -e POSTGRES_USER="$POSTGRES_USER" \
            -e POSTGRES_PASSWORD="$POSTGRES_PASSWORD" \
            -e POSTGRES_HOST="$POSTGRES_HOST" \
            -e GEMINI_API_KEY="$GEMINI_API_KEY" \
            -e ADMIN_EMAIL="$ADMIN_EMAIL" \
            -e FIREBASE_SERVICE_ACCOUNT="$FIREBASE_SERVICE_ACCOUNT" \
            -p 5000:5000 \
            budgetwise-backend)
          echo "Backend container ID: $BACKEND_ID"

          echo "Starting frontend container..."
          FRONTEND_ID=$(docker run --rm -d --name test-frontend \
            -e PUBLIC_BACKEND_API_URL="$PUBLIC_BACKEND_API_URL" \
            -e PUBLIC_FIREBASE_API_KEY="$PUBLIC_FIREBASE_API_KEY" \
            -e PUBLIC_FIREBASE_AUTH_DOMAIN="$PUBLIC_FIREBASE_AUTH_DOMAIN" \
            -e PUBLIC_FIREBASE_PROJECT_ID="$PUBLIC_FIREBASE_PROJECT_ID" \
            -e PUBLIC_FIREBASE_STORAGE_BUCKET="$PUBLIC_FIREBASE_STORAGE_BUCKET" \
            -e PUBLIC_FIREBASE_MESSAGING_SENDER_ID="$PUBLIC_FIREBASE_MESSAGING_SENDER_ID" \
            -e PUBLIC_FIREBASE_APP_ID="$PUBLIC_FIREBASE_APP_ID" \
            -p 3000:3000 \
            budgetwise-frontend)
          echo "Frontend container ID: $FRONTEND_ID"

          sleep 10

          echo "Checking container status..."
          docker ps -a

          echo "Checking container logs..."
          echo "Backend logs:"
          docker logs test-backend --tail 20 || true
          echo "Frontend logs:"
          docker logs test-frontend --tail 20 || true

          echo "Stopping containers..."
          # Stop containers if they're still running
          if docker ps -q --filter "name=test-backend" | grep -q .; then
            docker stop test-backend
          else
            echo "Backend container already stopped"
          fi

          if docker ps -q --filter "name=test-frontend" | grep -q .; then
            docker stop test-frontend
          else
            echo "Frontend container already stopped"
          fi


  
  # Test Summary
  test-summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: [backend-tests, frontend-tests]
    if: always()

    steps:
      - name: Check test results
        run: |
          echo "📊 Test Results Summary:"
          echo "Backend Tests: ${{ needs.backend-tests.result }}"
          echo "Frontend Tests: ${{ needs.frontend-tests.result }}"
          

          if [[ "${{ needs.backend-tests.result }}" == "success" && \
                "${{ needs.frontend-tests.result }}" == "success" ]]; then
            echo "✅ All tests passed! Production E2E testing successful."
            exit 0
          else
            echo "❌ Some tests failed!"
            echo "Backend: ${{ needs.backend-tests.result }}"
            echo "Frontend: ${{ needs.frontend-tests.result }}"
            
            exit 1
          fi
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run security audit on backend
        run: |
          cd backend
          npm audit --audit-level moderate

      - name: Run security audit on frontend
        run: |
          cd frontend
          npm audit --audit-level moderate